apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-office-deployment
  labels:
    app: dental-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dental-office
  template:
    metadata:
      labels:
        app: dental-office
    spec:
      containers:
      - name: dental-office
        image: migiburgos/dental-office
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dental-office-service
spec:
  type: LoadBalancer
  selector: 
    app: dental-office
  ports:
    - name: http
      port: 80
      targetPort: 8080